config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root "welcome#index"

	resources :historys
	get "/chapters/new/:id", to: "chapters#new", as: :new_chapter
	resources :chapters

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
	belongs_to :history
end

app/models/history.rb
class History < ApplicationRecord
	has_many :chapters

	validates_presence_of :name, :synopsi, :img_link
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

	def index
		@chapters = Chapter.all.reverse		
	end

	def new
		@history = History.find params[:id]
		@chapter = Chapter.new
	end

	def create
		@chapter = Chapter.new(chapter_params)

		if @chapter.save
			redirect_to chapter_path(@chapter.id)
		else
			render :new
		end
	end

	def edit
		@chapter = Chapter.find params[:id]
	end

	def update
		@chapter = Chapter.find params[:id]

		if @chapter.update_attributes(chapter_params)
			redirect_to chapter_path(@chapter.id)
		else
			render :edit
		end
	end

	def destroy
		@chapter = Chapter.find params[:id]
		@history_id = @chapter.history_id

		@chapter.destroy
		redirect_to history_path(@history_id)		
	end

	def show
		@chapter = Chapter.find params[:id]
	end

	private
	def chapter_params
		params.require(:chapter).permit(:number, :name, :context, :background_link, :history_id);
	end

end

app/controllers/historys_controller.rb
class HistorysController < ApplicationController

	def index
		@historys = History.all.reverse
	end

	def new
		unless current_user
			redirect_to historys_path
		else
			unless current_user.id <= 3
				redirect_to historys_path
			end
		end

		@history = History.new
	end

	def create
		@history = History.new(history_params)

		if @history.save
			redirect_to history_path(@history.id)
		else
			render :new
		end
	end

	def edit
		unless current_user
			redirect_to historys_path
		else
			unless current_user.id <= 3
				redirect_to historys_path
			end
		end
		
		@history = History.find params[:id]
	end

	def update
		@history = History.find params[:id]

		if @history.update_attributes(history_params)
			redirect_to history_path(@history.id)
		else
			render :edit
		end
	end

	def show
		@history = History.find params[:id]
	end

	def destroy
		@history = History.find params[:id]

		@history.destroy
		redirect_to historys_path
	end

	private 
	def history_params
		params.require(:history).permit(:name, :synopsi, :img_link, :by)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		@historys = History.last(2)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def nav_section
		if current_user
			render "layouts/with_user"
		else
			render "layouts/without_user"
		end
	end

	def btns_index_history
		if current_user
			if current_user.id <= 3
				render "btns_index_history"
			end
		end
	end

	def btns_show_history
		if current_user
			if current_user.id <= 3
				render "btns_show_history"
			end
		end
	end

	def btns_show_chapter
		if current_user
			if current_user.id <= 3
				render "btns_show_chapter"
			end
		end
	end

end

app/views/chapters/_btns_show_chapter.html.erb
<%= link_to "Apagar capítulo", 
	chapter_path(@chapter.id), 
	method: :delete, 
	class: "btn btn-danger form-control", 
	data: { confirm: "Deseja realmente apagar este capítulo?" } %>

<%= link_to "Editar capítulo",
	edit_chapter_path(@chapter.id),
	class: "btn btn-success form-control" %><br><br>

app/views/chapters/_form.html.erb
<script>
	function test_image(){
		document.getElementById("img-tester").src = document.getElementById("img-link").value;
	};
</script>

<%= simple_form_for @chapter, url: url do |chapter| %>
	<%= chapter.input :number, label: "Número do capítulo", error: "Este campo não pode ficar vázio." %>
	<%= chapter.input :name, label: "Nome", error: "Nome não pode ficar vazio." %>
	<%= chapter.input :context, as: :text, label: "Contexto", error: "É preciso ter uma história." %>
	<%= chapter.input :background_link, label: "Link de imagem de fundo", error: "Vai deixar tudo vazio mesmo?", input_html: {id: "img-link", onchange: "test_image();"} %>

	<div class="align-center">
		<p>Teste de imagem</p>
		<img src="#" style="width: 200px; height: 200px;" id="img-tester" >	
	</div>

	<div style="display: none;">
		<%= chapter.input :history_id, label: "history_id", error: "Este campo não deveria dar erro.", input_html: { value: @chapter.history_id.present? ? @chapter.history_id : @history.id } %>


		value: @history.id
	</div>

	<div class="align-right">
		<%= chapter.button :submit, "Criar Capítulo", class: "btn-primary" %>
	</div>
<% end %>

app/views/chapters/edit.html.erb
<div class="container">
	<h1 class="title-page">Editar capítulo: <%= @chapter.name %></h1>

	<div class="form-container">
		<%= render "form", url: false %>
	</div>
</div>

app/views/chapters/new.html.erb
<div class="container">
	<h1 class="title-page">Novo Capítulo</h1>

	<div class="form-container">
		<%= render "form", url: chapters_path %>
	</div>
</div>

app/views/chapters/show.html.erb
<div class="jumbotron" style="background-image: url('<%= @chapter.background_link %>');">
	<h1 class="chapter-title">...</h1>
</div>

<div class="container">
<h1 class="title-page"><%= "#{@chapter.number} - #{@chapter.name}" %></h1>

<%= btns_show_chapter %>

<pre class="history-context">
<%= @chapter.context %>
</pre>

</div>

app/views/historys/_btns_index_history.html.erb
<%= link_to new_history_path do %>
	<button class="btn btn-primary form-control">
		Adicionar nova história
	</button>
<% end %>

app/views/historys/_btns_show_history.html.erb
<%= link_to "Adicionar capítulo", 
	new_chapter_path(@history.id), 
	class: "btn btn-primary form-control" %>

<%= link_to "Apagar história", 
	history_path(@history.id), 
	method: :delete, 
	class: "btn btn-danger form-control", 
	data: { confirm: "Deseja realmente apagar está história?" } %>

<%= link_to "Editar história",
	edit_history_path(@history.id),
	class: "btn btn-success form-control" %>

app/views/historys/_form.html.erb
<script>
	function test_image(){
		document.getElementById("img-tester").src = document.getElementById("img-link").value;
	};
</script>

<%= simple_form_for @history, url: url do |history| %>
	<%= history.input :name, label: "Nome da história", error: "Nome não pode ficar vazio." %>
	<%= history.input :synopsi, label: "Sinopse", error: "Sinopse não pode ficar vazio." %>
	<%= history.input :img_link, label: "Link de imagem (icone)", error: "Vai deixar tudo vazio mesmo?", input_html: {id: "img-link", onchange: "test_image();"} %>

	<div class="align-center">
		<p>Teste de imagem</p>
		<img src="#" style="width: 200px; height: 200px;" id="img-tester" >	
	</div>
	

	<%= history.input :by, label: "Participantes", error: "Não sei por que estou aqui, esse pode ficar vazio." %>
	<div class="align-right">
		<%= history.button :submit, "Criar História",class: "btn-primary" %>
	</div>
<% end %>

app/views/historys/edit.html.erb
<div class="container">
	<h1 class="title-page">Editar História: <%= @history.name %></h1>	

	<div class="form-container">
		<%= render "form", url: false %>
	</div>
	
</div>

app/views/historys/index.html.erb
<div class="container">
	<h1 class="title-page">Histórias</h1>

	<div class="row">
		<div class="col-xs-1 col-sm-2">
		</div>

		<div class="col-xs-10 col-sm-8">

		 	<%= btns_index_history %>

			<% @historys.each do |history| %>
				<div class="media">
					<div class="media-left">
						<a href="">
							<%= image_tag history.img_link %>
						</a>
					</div>
					<div class="media-body">
						<h4 class="media-heading"><%= history.name %></h4>
						<p><%= history.synopsi %></p>
					</div>
					<div class="align-right">
						<%= link_to history_path(history.id) do || %>
							<button type="button" class="btn btn-success">
								<i class="material-icons">&#xE8F4;</i>
							</button>
						<% end %>
					</div>
				</div>
			<% end %>
			
		</div>

		<div class="col-xs-1 col-sm-2">
		</div>

	</div>

	
</div>

app/views/historys/new.html.erb
<div class="container">
	<h1 class="title-page">Nova História</h1>	

	<div class="form-container">
		<%= render "form", url: historys_path %>	
	</div>
	
</div>

app/views/historys/show.html.erb
<div class="container">
	<h1 class="title-page"><%= @history.name %> - Capitulos</h1>
	<p><%= @history.synopsi %></p>

	<div class="row">
		<div class="col-xs-1 col-sm-2">
		</div>

		<div class="col-xs-10 col-sm-8">

			<%= btns_show_history %>

			<% @history.chapters.each do |chapter| %>
				<div class="media">
					<div class="media-left">
						<a href="">
							<%= image_tag "#{@history.img_link}" %>
						</a>
					</div>
					<div class="media-body">
						<h4 class="media-heading"><%= "#{chapter.number} - #{chapter.name}" %></h4>
						<p>
							<%= chapter.context.first(120) + "..." %>
						</p>
					</div>
					<div class="align-right">
						<%= link_to chapter_path(chapter.id) do || %>
							<button type="button" class="btn btn-success">
								<i class="material-icons">&#xE8F4;</i>
							</button>
						<% end %>
					</div>
				</div>
			<% end %>

			<div class="align-center">
				<p><b>By: </b><%= @history.by %></p>
			</div>
		</div>

		

		<div class="col-xs-1 col-sm-2">
		</div>
</div>

app/views/layouts/_with_user.html.erb
<li><a href=""><%= current_user.email %></a></li>
<li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>

app/views/layouts/_without_user.html.erb
<li><%= link_to "Entrar", new_user_session_path %></li>
<li><%= link_to "Cadastrar", new_user_registration_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>WritersOfWorlds</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- ICON FONT -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>

    <!-- BOOTSTRAP3 - REFERENCE -->
    <!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

		<!-- BOOTSTRAP4 - DESIGN -->
    <!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid" style="padding-right: 5%;">
        <div class="navbar-header">

          <button
          type="button"
          class="navbar-toggle collapsed"
          data-toggle="collapse"
          data-target="#expand-nav"
          aria-expanded="false">
            <span class="sr-only">toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to root_path, class: "brand-success" do || %>
            <%= image_tag "logo.png", alt: "Brand", class: "Brand " %>
            Writers of Worlds
          <% end %>         
            
          </a>        
        </div>

        <div class="collapse navbar-collapse" id="expand-nav">
          <ul class="nav navbar-nav navbar-left">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Histórias", historys_path %></li>
            <%= nav_section %>
          </ul>
        </div>      
        
      </div>
    </nav>
  
  	<div style="height: 65px;"></div>		
  	<%= yield %>

    <footer style="text-align: center; padding: 20px 0;">
      <p>@2016 - Writers of Words</p>
    </footer>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<h1>Writers Of World</h1>
	<p>O mundo que você já conhece, agora de uma maneira que você nunca viu!</p>
	<%= image_tag "logo.png", style: "width: 250px;" %><br><br>
	<p class="btn btn-success btn-lg"> Histórias </p>
</div>

<h1 class="title-container">Navegue entre mundos!</h1>

<div class="row" style="width: 100%;">
	<div class="col-xs-1 col-md-2"></div>
	<div class="col-xs-11 col-md-8" style="margin: 0 auto;">

		<% @historys.each do |history| %>
			<div class="media">
				<div class="media-left">
					<a href="">
						<%= image_tag history.img_link %>
					</a>
				</div>
				<div class="media-body">
					<h4 class="media-heading"><%= history.name %></h4>
					<p><%= history.synopsi %></p>
				</div>
				<div class="align-right">
					<%= link_to history_path(history.id) do || %>
						<button type="button" class="btn btn-success">
							<i class="material-icons">&#xE8F4;</i>
						</button>
					<% end %>
				</div>
			</div>
		<% end %>

	</div> <!-- END COL-XS-11 -->
</div> <!-- END ROW -->